export const environment = {
  production: false,
  canaldeventadefault: '2015000002',
  puntodeventadefault: '2',
  codigocomercio: '522591303',
  codigocomercioTP: '522591303',
  codigocomercioVidaLey: '522591303',
  codigocomercioATP: '522591303',
  codigocomercioAP: '522591303',
  codigocomercioSctr: '522591303',
  codigocomercioRenovacion: '522591303',
  codigoComercioShop: '522591303',
  trackIdAP: 'UA-215670846-2',
  trackIdVDP: 'GTM-KGHZP6F',
  tagManagerIdAP: 'GTM-WK2KZH2',
  bigPrime: 'af9a07878e764c0dbbc3e55a498a3661',
  recaptchaKey: '6Lfn13QmAAAAAOWGyLtu78ZrvpSq4-n_xZjw-Kaz',
  recaptchaKeySoat: '6LfxPsgqAAAAAPHSDdlKhM0QPPaEMwpqUxF3JUik',
  apiBigprime: 'https://rekognition.bigprime.pe',
  pagoefectivoservice: 'https://pre1a.pagoefectivo.pe/genpagoif.aspx',
  visabuttonservice:
    'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
  visabuttonserviceRenovacion:
    'https://static-content-qas.vnforapps.com/vToken/js/checkout.js',
  versioncheckurl: 'http://localhost:4200/version.json',
  kunturapi: 'http://localhost:30897/Api',
  //kunturapi: 'https://serviciosqa.protectasecurity.pe/WSKunturQA/Api',
  reportapi: 'http://10.10.1.56:80/WSREPORTAPIQA/api',
  scoringapi: 'https://servicios360.protectasecurity.pe/qa/api',
  //backendapi: 'https://servicios.protectasecurity.pe/WSPlataformaDigital/api',
  backendapi: 'https://serviciosqa.protectasecurity.pe/WSPlataformadigitalQas/api',
  //backendapi: 'https://servicesdev.protectasecurity.pe/wsplataformadigital/api',
  wspdApi: 'https://servicesdev.protectasecurity.pe/wspd/api',
  wspdApiAWS: 'https://serviciosqa.protectasecurity.pe/wspdqaAWS/api',
  //wspdApi: 'https://serviciosqa.protectasecurity.pe/wspd/api',
  //wspdApiAWS: 'http://localhost:2085/api',
  backofficeApi: 'https://serviciosqa.protectasecurity.pe/backofficeqa',
  domainurl: 'http://localhost:4200',
  domain: 'http://localhost:4200',
  descargacomprobanteapi:
    'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/DescargarMasivo',
  validarcomprobanteapi:
    'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/ValidarCDR',
    aws: {
        region: 'us-east-1',
        graphqlApi: 'https://api.tcdg.stg.protectasecuritycloud.pe/graphql',
        graphqlApiKey: 'da2-4xu3yayat5dw3bax6fomlpllfq',
    },
  version: require('../../package.json').version + '-qa',
  ideconapi: 'https://serviciosqa.protectasecurity.pe/IdeconApiQa/API',
  reg_negativo_api: 'https://serviciosqa.protectasecurity.pe/RegNegativoApiQA/API',
  worldcheckapi: 'https://serviciosqa.protectasecurity.pe/WC1APIQA/API',
  useEncryption: false,
  aesKey: 'nXZr4M7wLqTY82uJ',
  aesIV: 'aSDfadsfsdf873SD',
  apiOtpAws: 'https://api.nntp-dev.protectasecuritycloud.pe'
};
