export const environment = {
    production: false,
    canaldeventadefault: '2015000002',
    puntodeventadefault: '2',
    codigocomercio: '522591303',
    codigocomercioTP: '522591303',
    codigocomercioVidaLey: '522591303',
    codigocomercioATP: '522591303',
    codigocomercioAP: '522591303',
    codigocomercioSctr: '522591303',
    codigocomercioRenovacion: '522591303',
    codigoComercioShop: '522591303',
    trackIdAP: 'UA-215670846-2',
    trackIdVDP: 'GTM-KGHZP6F',
    tagManagerIdAP: 'GTM-WK2KZH2',
    bigPrime: 'af9a07878e764c0dbbc3e55a498a3661',
    recaptchaKey: '6LeQ23QmAAAAAJ7hWePKtgl33h3itfd9vT2HXUv9',
    recaptchaKeySoat: '6LfxPsgqAAAAAPHSDdlKhM0QPPaEMwpqUxF3JUik',
    apiBigprime: 'https://rekognition.bigprime.pe',
    pagoefectivoservice: 'https://pre1a.pagoefectivo.pe/genpagoif.aspx',
    visabuttonservice:
        'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
    visabuttonserviceRenovacion:
        'https://static-content-qas.vnforapps.com/vToken/js/checkout.js',
    versioncheckurl:
        'https://serviciosqa.protectasecurity.pe/plataformadigital-qas-new/version.json',
    kunturapi: 'https://serviciosqa.protectasecurity.pe/WSKunturQA/Api',
    reportapi: 'http://10.10.1.56:80/WSREPORTAPIQA/api',
    scoringapi: 'https://servicios360.protectasecurity.pe/qa/api',
    backendapi:'https://servicesdev.protectasecurity.pe/wsplataformadigital/api',
    // backendapi: 'http://localhost:30897/api',
    wspdApi: 'https://serviciosqa.protectasecurity.pe/wspdstg/api',
    wspdApiAWS: 'https://serviciosqa.protectasecurity.pe/wspdqaqas/api',
    backofficeApi: 'https://serviciosqa.protectasecurity.pe/backofficeqa',
    domainurl: 'https://serviciosqa.protectasecurity.pe/plataformadigital-qas-new',
    domain: 'https://serviciosqa.protectasecurity.pe/plataformadigital-qas-new',
    descargacomprobanteapi:
        'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/DescargarMasivo',
    validarcomprobanteapi:
        'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/ValidarCDR',
    aws: {
        region: 'us-east-1',
        graphqlApi: 'https://api.tcdg.stg.protectasecuritycloud.pe/graphql',
        graphqlApiKey: 'da2-4xu3yayat5dw3bax6fomlpllfq',
    },
    version: require('../../package.json').version + '-qa',
    ideconapi: 'https://serviciosqa.protectasecurity.pe/IdeconApiQa/API',
    reg_negativo_api: 'https://serviciosqa.protectasecurity.pe/RegNegativoApiQA/API',
    worldcheckapi: 'https://serviciosqa.protectasecurity.pe/WC1APIQA/API',
    useEncryption: false,
  aesKey: 'nXZr4M7wLqTY82uJ',
  aesIV: 'aSDfadsfsdf873SD'
};
