export const environment = {
    production: true,
    canaldeventadefault: '2015000002',
    puntodeventadefault: '2',
    codigocomercio: '522591303',
    codigocomercioTP: '522591303',
    codigocomercioVidaLey: '522591303',
    codigocomercioATP: '522591303',
    codigocomercioAP: '522591303',
    codigocomercioSctr: '522591303',
    codigocomercioRenovacion: '522591303',
    codigoComercioShop: '522591303',
    trackIdAP: 'UA-215670846-2',
    trackIdVDP: 'GTM-KGHZP6F',
    tagManagerIdAP: 'GTM-WK2KZH2',
    bigPrime: 'af9a07878e764c0dbbc3e55a498a3661',
    recaptchaKey: '6Lfn13QmAAAAAOWGyLtu78ZrvpSq4-n_xZjw-Kaz',
    recaptchaKeySoat: '6LfxPsgqAAAAAPHSDdlKhM0QPPaEMwpqUxF3JUik',
    pagoefectivoservice: 'https://pre1a.pagoefectivo.pe/genpagoif.aspx',
    visabuttonservice:
      'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
    visabuttonserviceRenovacion:
      'https://static-content-qas.vnforapps.com/vToken/js/checkout.js',
    versioncheckurl:
      'https://soatservicios.protectasecurity.pe/staging/version.json',
    kunturapi: 'https://serviciosqa.protectasecurity.pe/WSKuntur/Api',
    reportapi: 'http://10.10.1.56:80/WSREPORTAPIQA/api',
    scoringapi: 'https://servicios360.protectasecurity.pe/qa/api',
    backendapi:
      'https://serviciosqa.protectasecurity.pe/WSPlataformadigitalQas/api',
    wspdApi: 'https://serviciosqa.protectasecurity.pe/wspdqas/api',
    wspdApiAWS: 'https://serviciosqa.protectasecurity.pe/wspdqaAWS/api',
    //wspdApi: 'https://serviciosqa.protectasecurity.pe/wspdqaMG/api',
    //wspdApi: 'https://serviciosqa.protectasecurity.pe/wspd/api',
    backofficeApi: 'http://190.216.170.173/backofficeqa',
    domainurl: 'https://soatservicios.protectasecurity.pe/staging',
    domain: 'soatdigital.protectasecurity.pe',
    descargacomprobanteapi:
      'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/DescargarMasivo',
    validarcomprobanteapi:
      'https://serviciosqa.protectasecurity.pe/efacturacion/api/Comprobante/ValidarCDR',
    version: require('../../package.json').version + '-qa',
  ideconapi: 'https://serviciosqa.protectasecurity.pe/IdeconApiQa/API',
  reg_negativo_api: 'https://serviciosqa.protectasecurity.pe/RegNegativoApiQA/API',
  worldcheckapi: 'https://serviciosqa.protectasecurity.pe/WC1APIQA/API',
  useEncryption: false,
  aesKey: 'nXZr4M7wLqTY82uJ',
  aesIV: 'aSDfadsfsdf873SD',
  apiOtpAws: 'https://api.nntp-dev.protectasecuritycloud.pe'
};
