export const environment = {
  production: false,
  canaldeventadefault: '2015000002',
  puntodeventadefault: '2',
  codigocomercio: '522591303',
  codigocomercioTP: '522591303',
  codigocomercioVidaLey: '522591303',
  codigocomercioATP: '522591303',
  codigocomercioAP: '522591303',
  codigocomercioRenovacion: '522591303',
  codigocomercioSctr: '522591303',
  codigoComercioShop: '522591303',
  trackIdAP: 'UA-215670846-2',
  trackIdVDP: 'GTM-KGHZP6F',
  tagManagerIdAP: 'GTM-WK2KZH2',
  bigPrime: 'e937528869ca4cea92101e0ddbdf1c0511',
  recaptchaKey: '6LfH03QmAAAAAAN4L_ZDzPibRHyQrwNJMGz3lCB4',
  recaptchaKeySoat: '6LfxPsgqAAAAAPHSDdlKhM0QPPaEMwpqUxF3JUik',
  apiBigprime: 'https://rekognition.bigprime.pe',
  pagoefectivoservice: 'https://pre1a.pagoefectivo.pe/genpagoif.aspx',
  visabuttonservice:
    'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
  visabuttonserviceRenovacion:
    'https://static-content-qas.vnforapps.com/vToken/js/checkout.js?qa=true',
  versioncheckurl: 'http://localhost:4200/version.json',
  backendapi: 'http://localhost:4200/api',
  wspdApi: 'https://servicios.protectasecurity.pe/wspdstg/api',
  wspdApiAWS: 'https://serviciosqa.protectasecurity.pe/wspdqaAWS/api',
  backofficeApi: 'http://localhost:4200/api/backofficeqa',
  kunturapi: 'http://190.216.170.173/wskunturvt7/Api',
  reportapi: 'https://localhost:44315/api/',
  domainurl: 'http://localhost:4200',
  domain: 'localhost',
  descargacomprobanteapi:
    'https://servicesdev.protectasecurity.pe/efacturacion/api/Comprobante/DescargarMasivo',
  validarcomprobanteapi:
    'https://servicesdev.protectasecurity.pe/efacturacion/api/Comprobante/ValidarCDR',
  plataformaDigitalApi: 'https://servicios.protectasecurity.pe/wspdstg',
  version: require('../../package.json').version + '-local',
  useEncryption: false,
  aesKey: 'nXZr4M7wLqTY82uJ',
  aesIV: 'aSDfadsfsdf873SD'
};
